### ISSUE TITLE
Calculator example cannot run

### ISSUE THREAD

**Issue by yoshijava** [pfmiles/dropincc.java#29]
I tried to run the example in the directory (Calculator.java), and it didn't work.

JVM version:
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

Message:
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: com.github.pfmiles.dropincc.DropinccException: java.lang.NullPointerException
        at com.github.pfmiles.dropincc.impl.hotcompile.HotCompileUtil.compile(HotCompileUtil.java:72)
        at com.github.pfmiles.dropincc.impl.AnalyzedLang.compile(AnalyzedLang.java:165)
        at com.github.pfmiles.dropincc.Lang.compile(Lang.java:113)
        at Calculator.<clinit>(Calculator.java:77)
Caused by: java.lang.NullPointerException
        at com.github.pfmiles.dropincc.impl.hotcompile.HotCompileUtil.compile(HotCompileUtil.java:70)
        ... 3 more

**Comment by pfmiles** [comment]
hi , which operating system do you use? I cannot reproduce this issue in java 10.0.2 on macosx Catalina 10.15.3.
